version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    container_name: ElasticDB
    network_mode: "host"
    environment:
      node.name: es01
      cluster.name: $CLUSTER_NAME
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
      xpack.security.enabled: $ELASTIC_SECURITY
    volumes:
      - ./data:/usr/share/elasticsearch/data:rw
      - ./certs:/usr/share/elasticsearch/config/certs:rw
    ports:
      - "127.0.0.1:9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3